# NumCompute Quickstart (Iris)

This notebook demonstrates the core modules with `demo/iris.csv` and `demo/iris_missing.csv` datasets.

In [6]:
import numpy as np
from numcompute.io import load_csv
from numcompute.sort_search import binary_search, quickselect, topk, stable_sort
from numcompute.rank import percentile, rank
from numcompute.metrics import accuracy, confusion_matrix, f1, mse, precision, recall
from numcompute.preprocessing import StandardScaler, MinMaxScaler, SimpleImputer, OneHotEncoder
from numcompute.pipeline import Pipeline

## 1) Load CSV with `io.py`

In [7]:
filename = 'iris.csv'
# species is string -> parsed as NaN in load_csv (expected)
raw_numeric = load_csv(filename, skip_rows=1)
print('Shape:', raw_numeric.shape)
print('NaN count:', int(np.isnan(raw_numeric).sum()))
print('First row:', raw_numeric[0])

# Load the missing data version to show NaN handling in stats/metrics
filename_missing = 'iris_missing.csv'
raw_missing = load_csv(filename_missing, skip_rows=1)
print('Shape (missing):', raw_missing.shape)
print('NaN count (missing):', int(np.isnan(raw_missing).sum()))

# Load missing data with NaN filling to show preprocessing
raw_filled = load_csv(filename_missing, skip_rows=1,
                      fill_value=99.99)  # for demo purposes only, not a real imputation strategy
print('Shape (filled):', raw_filled.shape)
print('NaN count (filled):', int(np.isnan(raw_filled).sum()))

Shape: (150, 5)
NaN count: 150
First row: [5.1 3.5 1.4 0.2 nan]
Shape (missing): (150, 5)
NaN count (missing): 222
Shape (filled): (150, 5)
NaN count (filled): 0


## 2) Preprocessing + pipeline

In [8]:


#get only numeric columns (first 4, drop species which is NaN)
X = raw_missing[:, :4]
print("Shape before imputing:", X.shape)
print("NaN count before:", int(np.isnan(X).sum()))


#build a pipeline impute NaN then scale
pipe = Pipeline([
    ("imputer", SimpleImputer(strategy="mean")),
    ("scaler", StandardScaler())
])

X_out = pipe.fit_transform(X)
print("NaN count after:", int(np.isnan(X_out).sum()))
print("Mean per column :", np.round(np.mean(X_out, axis=0), 4))
print("Std per column :", np.round(np.std(X_out, axis=0), 4))


Shape before imputing: (150, 4)
NaN count before: 72
NaN count after: 0
Mean per column : [-0. -0. -0. -0.]
Std per column : [1. 1. 1. 1.]


In [9]:
#MinMaxScaler 
pipe2 = Pipeline([
    ("imputer", SimpleImputer(strategy="mean")),
    ("scaler", MinMaxScaler(feature_range=(0, 1)))
])

X_minmax = pipe2.fit_transform(X)
print("Min per column :", np.round(np.min(X_minmax, axis=0), 4))
print("Max per column :", np.round(np.max(X_minmax, axis=0), 4))

Min per column : [0. 0. 0. 0.]
Max per column : [1. 1. 1. 1.]


In [10]:
# comparison original vs processed (first 10 rows)
print("Original (first 10 rows):")
print(np.round(X[:10], 4))

Original (first 10 rows):
[[5.1 3.5 nan 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [nan 3.4 1.4 nan]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 nan]
 [4.9 3.1 1.5 0.1]]


In [11]:
print("\nProcessed - StandardScaler (first 10 rows):")
print(np.round(X_out[:10], 4))


Processed - StandardScaler (first 10 rows):
[[-0.959   1.1096 -0.     -1.4233]
 [-1.2171 -0.1212 -1.4631 -1.4233]
 [-1.4752  0.3711 -1.5262 -1.4233]
 [-1.6042  0.1249 -1.4    -1.4233]
 [-1.088   1.3557 -1.4631 -1.4233]
 [-0.5719  2.0942 -1.2739 -1.1444]
 [-0.      0.8634 -1.4631 -0.    ]
 [-1.088   0.8634 -1.4    -1.4233]
 [-1.8623 -0.3674 -1.4631 -0.    ]
 [-1.2171  0.1249 -1.4    -1.5628]]


## 3) sort_search + rank

## 4) stats + metrics + optim

## 5) Benchmark snapshot